version: '2'
services:
  mongo:
    image: mongo:4.0
    volumes:
      - vmongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
volumes:
  vmongo: null
networks:
  backend: null
