version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8 
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Copy config private
          command: cp config.private.ts.example config.private.ts      
      - run:
          name: lint
          command: npm run lint
      - run:
          name: tsc
          command: npm run tsc
      - run:
          name: test
          command: npm run test
